name: Publish to Pypi - vllm-ft
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to upload to pypi'
        required: true
      pypi_repo:
        description: 'Repo to upload to (testpypi or pypi)'
        default: 'testpypi'
        required: true

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Linux Env
        run: bash -x .github/workflows/scripts/env.sh
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install CUDA 12.1
        run: bash -x .github/workflows/scripts/cuda-install.sh '12.1' 'ubuntu-24.04'
      - name: Install PyTorch 2.6.0 with CUDA 12.1
        # The pytorch version (2.6.0) must be the most recent version that meets requirements/cuda.txt.
        run: bash -x .github/workflows/scripts/pytorch-install.sh '3.11' '2.6.0' '12.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Make easy_install.sh executable
        run: chmod +x easy_install.sh
      - name: Set the environment variables
        run: |
          echo "VLLM_PRECOMPILED_WHEEL_LOCATION=$(./easy_install.sh --env-only)" >> $GITHUB_ENV
      - name: Test
        run: echo $VLLM_PRECOMPILED_WHEEL_LOCATION
      - name: Build package
        run: python -m build
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
        if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
        if: ${{ github.event.inputs.pypi_repo == 'pypi' }}